### ISSUE TITLE
Add option to start with a different color theme

### ISSUE THREAD

**Issue by garret** [joshdk/tty-qlock#10]
I use alacritty with monokai color scheme and unfortunately the not highlighted words just hides in the background. This does not happen when I change the color scheme (e.g., dracula) where the black color is very different from the background color. 

Would it be possible to add some sets of themes to improve the reading when in such situations like above? For instance, in my case it would be nicer to have the not highlighted words more grayish to stand out more.

**Comment by joshdk** [comment]
Totally agree! I'll probably implement this with a `--color` and `--background` command line flag.

**Comment by joshdk** [comment]
@garret Want to check out #12 and see if that works for your setup? Would be good to get more data!

**Comment by garret** [comment]
@joshdk I could try that but I don't know how to install the application. Before I had just downloaded the script and executed it. Maybe an installation guide could be added in the README?

**Comment by joshdk** [comment]
Absolutely, I'll be revamping the docs when I address #6. In the meantime, I show how to run the program in #12, like so:

```
$ go run main.go -on-color green+bold -off-color black
```

I'm also working on publishing pre-compiled release binaries, so that folks can just download and run stuff, without needing to build anything.

**Comment by garret** [comment]
I `git-cloned` the repo, `cd `into the repo and gave that command. However, even by changing the `green` and `black` options with other colors, I always get the clock to be displayed with black background, black not highlighted words (so the words hide with the background), while the highlighted text is purple. I am using alacritty with monokai color scheme. Therefore, it seems it is not really working for me or I am doing something wrong.

**Comment by joshdk** [comment]
Could you upload a screenshot please (maybe with an annotation pointing to the exact elements)? I want to get things working for you!

**Comment by garret** [comment]
So this happens when I give this: 
```
[garret@void ~]$ cd tty-qlock/
[garret@void tty-qlock]$ go run main.go -on-color green+bold -off-color black
```
![image](https://user-images.githubusercontent.com/27555/96295248-ddee9b80-0fed-11eb-8cb6-000297547879.png)

Then I give this: 
```
[garret@void tty-qlock]$ go run main.go -on-color black+bold -off-color green
```
And still gets the same result: 
![image](https://user-images.githubusercontent.com/27555/96295333-ffe81e00-0fed-11eb-9ccb-aca9cd548cf3.png)

**Comment by joshdk** [comment]
@garret could you please make sure that you have checked out the `joshdk/color-flags` branch locally? The color flags don't have any impact if you aren't on that PR branch. Thank you!

```
$ git checkout master
$ git fetch origin joshdk/color-flags:joshdk/color-flags
$ git checkout joshdk/color-flags
$ go run main.go ...etc
```
